### ISSUE TITLE
Emojis won't render/work from lists using "letter of" block

### ISSUE THREAD

**Issue by Scratchfangs** [TurboWarp/scratch-vm#128]
### Expected Behavior

![image](https://user-images.githubusercontent.com/71499307/233508916-6cd253cf-3060-4060-8e76-880f9586ac90.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/71499307/233508927-a49c9058-b92a-46ef-9a2a-6a8db94095c9.png)

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/71499307/233509074-c159705c-43c3-4d4e-8d39-63b2e63e0350.png)

### Operating System and Browser

Edge 112.0.1722.48, Windows 11

**Comment by GarboMuffin** [comment]
this is also a Scratch issue and a JavaScript issue in general

**Comment by Johan-Mi** [comment]
This happens because string indexing in Scratch uses UTF-16 code units (16 bits each) instead of Unicode code points (what's typically considered a "character"). Using code points would fix this specific case but would make string indexing $O(n)$ since code points aren't all the same length. The even more correct solution would be to use *grapheme clusters*, which among other things count letters with diacritics as one character and support composed emoji like skin tones and country flags. This would also be $O(n)$.

**Comment by GarboMuffin** [comment]
Yeah, we can't change this without breaking Scratch compatibility, and it would be slow

Seems like something that would work well in an extension
