### ISSUE TITLE
Compiler Support

### ISSUE THREAD

**Issue by 0832k12** [TurboWarp/scratch-vm#206]
Let extensions access the compiler.
like this:
![image](https://github.com/TurboWarp/scratch-vm/assets/70421730/7089c724-bdbc-47af-8cda-b685f3044e63)
![image](https://github.com/TurboWarp/scratch-vm/assets/70421730/fa25f2c1-dd92-4283-b3d5-014a0cc8d8f4)

**Comment by FurryR** [comment]
Duplicate issue (https://github.com/TurboWarp/scratch-vm/pull/181).
Maybe you can ask for more exports.

**Comment by 0832k12** [comment]
🧠

**Comment by LilyMakesThings** [comment]
Extensions can access the compiler already (and they are soon to be "supported"), but you won't receive any help with them.

Extensions are designed in such a way that you aren't supposed to need to access the compiler, because if you were able to it'd suddenly become 2 extensions essentially, which means 2 environments all the blocks have to be tested in, and it becomes double the work.

With how they're written at the moment, all the functions and such are verified to work in both the interpreter and the compiler and there's not much need to test each environment, except some rare cases.

Some extensions have blocks that genuinely cannot work without access to the compiler and in those cases, said exports do exist. However they don't come with documentation nor instruction on how to use them, and if they break, that's your fault.
