### ISSUE TITLE
Reconsider using custom procedure argument reporters to implement custom blocks

### ISSUE THREAD

**Issue by GarboMuffin** [TurboWarp/scratch-vm#44]
Moved from #30, see comments there for arguments for and against

**Comment by MiniCoder11** [comment]
I may come up with further reasons in the future, but for now I think the only thing I can add to my other post is that projects with the new TurboWarp-exclusive blocks cannot be shared on Scratch. This means you cannot have the project hosted easily or discovered by the community without posting a link (which does not give anyone a notification that a shared project would and also does not keep track of view/heart/star statistics). In addition, Scratch seems to particularly dislike the new(ish) mouse blocks and occasionally proceeds to eternally show the loading page when you attempt to upload a project with them in it. Although the TurboWarp editor is very nice (I've switched over to using it for many large-scale projects), there is no way to save project to a magical TurboWarp server somewhere (which you don't want to maintain or pay for for very understandable reasons) so our only way of viewing other's projects are through download links (not allowed on Scratch) and through regular project IDs which require only normal Scratch blocks to exist in order to load.

All in all, if I'm understanding TurboWarp's intended use correctly (to run Scratch projects at faster speeds and to loosen the limits that limit creativity in Scratch), then adding custom blocks to support the actual project being loaded makes sense so that we can share projects with the great features of TurboWarp and still have a version on Scratch for everyone to see.

**Comment by GarboMuffin** [comment]
I've thought about this more.

Using custom procedure arguments is still not going to happen, but maybe the "key pressed" block could be extended to support last key pressed and even mouse cursors.

**Comment by MiniCoder11** [comment]
That sounds like a fair compromise.

**Comment by GarboMuffin** [comment]
ship has sailed with https://extensions.turbowarp.org/
