### ISSUE TITLE
DCPU emulator crashes when anything is selected.

### ISSUE THREAD

**Issue by Sasytoremember** [TurboWarp/scratch-vm#79]
### Expected Behavior

What should happen is that the emulator starts emulating that ROM.

### Actual Behavior

Instead the entire web page stops to a halt, unable to click anything.

### Steps to Reproduce

Go to turbowarp.org/11693479
Select an option using the arrow keys to select and space to execute ROM.

### Operating System and Browser

ChromeOS 103.0.5060.37

**Comment by Sasytoremember** [comment]
Works with Phosphorus, Forkphorus, and vanilla Scratch.

**Comment by GarboMuffin** [comment]
The project tries to use the timer block to only run for 33ms, but Scratch 3 changed the timer block to always return the same value throughout a frame, so this becomes an infinite in a run w/o screen refresh loop. Scratch will run the project at 2 FPS because it has a warp timer, but TurboWarp's warp timer is disabled by default for performance, so the loop never ends.

The easiest workaround is to mark the "Step CPU" custom block as not run without screen refresh.

Ideally the compiler would be smart enough to notice this pattern as we've seen it quite a few times

**Comment by Sasytoremember** [comment]
Thanks, I can now play these cool little mini-games
